version: '2'

services: 
  mysql:
    container_name: abntextor_mysql
    restart: unless-stopped
    image: mysql:5.7.29
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    container_name: abntextor
    restart: unless-stopped
    build: .
    ports: 
      - "3000:3000"
    environment:
      APP_MYSQL_DATABASE: ${MYSQL_DATABASE}
      APP_MYSQL_DATABASE_USER: ${MYSQL_USER}
      APP_MYSQL_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/app/

volumes:
  mysql-data:
    external: false